version: '3'

services:
  mongodb:
    container_name: talkdater_mongo
    build: ./mongodb
    ports:
      - "27017:27017"
    networks:
      - dockernet

  api:
    container_name: talkdater_api
    build: ./api
    command: nodemon index.js
    volumes:
      - ./api/:/usr/src/app/
    depends_on:
      - mongodb
    networks:
      - dockernet
    environment:
      - NODE_ENV=development
    restart: always

  client:
    container_name: talkdater_client
    # build: ./client
    image: httpd:alpine
    volumes: 
      # the following trick is for deve purposes only
      - ./client/build/default/:/usr/local/apache2/htdocs/
    depends_on:
      - mongodb
      - api
    networks:
      - dockernet

  reverseproxy:
    container_name: talkdater_proxy
    ports:
      - 80:8080
    build: ./reverseproxy
    depends_on:
      - api
      - client
    restart: always
    networks:
      - dockernet

networks:
  dockernet: